### ISSUE TITLE
run_tests needs certain latex packages such as texlive-latex-extra (ubuntu linux)

### ISSUE THREAD

**Issue by smcpeak** [seL4/l4v#11]
I recently got "run_tests" in the l4v repository to pass on an Ubuntu 14.04 Linux system and needed to install several additional packages in order for the latex calls to succeed.  I recommend adding the following to the instructions in README.md:

`$ sudo apt-get install texlive-fonts-recommended texlive-latex-extra texlive-metapost texlive-bibtex-extra
`

In case it matters, here is what each package is needed for:

- Test CamkesAdlSpec (among others) fails due to missing font "ptmr7t" without texlive-fonts-recommended.

- Tests ASpec fails due to missing "fixme.sty" without texlive-latex-extra.

- Test HaskellKernel fails due to mpost missing its preload files without texlive-metapost.  (This one seems to be in part due to an Ubuntu [packaging error](https://bugs.launchpad.net/ubuntu/+source/texlive-bin/+bug/1334143).)

- Test AutoCorresDoc fails due to missing "plainurl.bst" without texlive-bibtex-extra.

**Comment by lsf37** [comment]
Very good, thanks for spotting these, will add. It's hard to keep these up to date while things develop and the test machines have fairly comprehensive installs.

**Comment by lsf37** [comment]
Now done in 081c733.
