### ISSUE TITLE
errors happen using proof  count

### ISSUE THREAD

**Issue by LVPGroup** [seL4/l4v#12]
Hi, I am using proofcount with Isabelle 2016 in Ubuntu. Some errors occur as follows.

Could you help to correct them? thanks.

---

zhaoyw@zhaoyw-VirtualBox:~/research$ isabelle proofcount -x xkernel.xml -d xkernel -L XKernel -T SK_L2Spec
Starting ProofCount...
Making new metric file at /home/zhaoyw/research/xkernel.xml. Running Isabelle...
Building XKernel ...
Document at /home/zhaoyw/research/xkernel/output/document.pdf
Finished XKernel (0:05:53 elapsed time, 0:06:38 cpu time, factor 1.12)
Running ProofCount_Exec ...

ProofCount_Exec FAILED
(see also /home/zhaoyw/.isabelle/Isabelle2016/heaps/polyml-5.6_x86_64-linux/log/ProofCount_Exec)

**\* ML error (line 86 of "~/software/proofcount/proof_count.ML"):
**\* Type error in function application.
**\*    Function: wrap_lthy' :
**\*       Keyword.keywords ->
**\*         (Token.T list -> ('a -> Proof.context -> Proof.context) \* 'b) ->
**\*           Token.T list -> ('a -> Proof.context -> Proof.context) \* 'b
**\*    Argument: "lemmas" : string
**\*    Reason:
**\*       Can't unify Keyword.keywords with string (_In Basis_)
**\*          (Different type constructors)
**\* ML error (line 86 of "~/software/proofcount/proof_count.ML"):
**\* Value or constructor (lemmaK) has not been declared in structure Thm
**\* ML error (line 188 of "~/software/proofcount/proof_count.ML"):
**\* Type error in function application.
**\*    Function: add_new_lemmas thy thy' pos pos : Keyword.keywords -> unit
**\*    Argument: name : string
**\*    Reason:
**\*       Can't unify Keyword.keywords with string (_In Basis_)
**\*          (Different type constructors)
**\* At command "ML_file" (line 15 of "~/software/proofcount/ProofCount.thy")
Unfinished session(s): ProofCount_Exec
0:06:34 elapsed time, 0:06:58 cpu time, factor 1.06
isabelle processing proofcount failed

**Comment by lsf37** [comment]
Proofcount is indeed currently broken for Isabelle2016 and its maintainer is on long-term leave on an internship, so it'll be a few months until we can fix this, sorry.

**Comment by ywzh** [comment]
Dear, I have tried Isabelle2015 in Win8, but got the same errors. Which version of Isabelle and OS I can use? 

Thanks a lot.

**Comment by danmatichuk** [comment]
There is a more up-to-date version which should work with Isabelle 2015 here: https://bitbucket.org/daniel_matichuk/proofcount

I am currently working on one for the upcoming Isabelle release: 2016-1

**Comment by YakoubN** [comment]
Guys,

For some reason Isabelle did not manage to compile the theory Word_Lemmas_64 on a Guest Ubuntu running on VMware. But with the same exact setup for Ubuntu I can compile it on a machine with a double-boot.

Any help to fix this. See the error in the sequel.

------------------------------------------------------------------------
TEST FAILED: isabelle

...
Word_Lib: theory Signed_Words
Word_Lib: theory Norm_Words
Word_Lib: theory WordBitwise_Signed
Word_Lib: theory Word_Syntax
Word_Lib: theory Word_Lib
Word_Lib: theory Aligned
Word_Lib: theory Word_Enum
Word_Lib: theory Word_Lemmas
Word_Lib: theory Word_Setup_32
Word_Lib: theory Word_Lemmas_32
Word_Lib: theory Word_Setup_64
Word_Lib: theory Word_Lemmas_64
*** Timeout
Word_Lib FAILED
(see also /home/yakoub/.isabelle/heaps-ARM-home-yakoub-Desktop-verification-isabelle/polyml-5.6_x86_64-linux/log/Word_Lib)

instantiation
  Enum.finite_3 :: len
  len_of_finite_3 == len_of :: Enum.finite_3 itself \<Rightarrow> nat
instantiation
  word :: (len) wellorder
linarith_split_limit exceeded (current value is 9)
linarith_split_limit exceeded (current value is 9)
### theory "Word_Lemmas"
### 98.703s elapsed time, 97.708s cpu time, 1.412s GC time
Loading theory "Word_Setup_32" (required by "Word_Lemmas_32")
### theory "Word_Setup_32"
### 0.097s elapsed time, 0.096s cpu time, 0.000s GC time
Loading theory "Word_Lemmas_32"
### theory "Word_Lemmas_32"
### 7.227s elapsed time, 7.128s cpu time, 0.084s GC time
Loading theory "Word_Setup_64" (required by "Word_Lemmas_64")
### theory "Word_Setup_64"
### 0.104s elapsed time, 0.104s cpu time, 0.000s GC time
Loading theory "Word_Lemmas_64"
*** Interrupt
Unfinished session(s): Word_Lib
Finished at Wed Dec 14 12:03:18 PST 2016
0:18:05 elapsed time, 0:18:01 cpu time, factor 0.99

------------------------------------------------------------------------
TEST FAILED: HaskellKernel

cabal sandbox init
make: cabal: Command not found
Makefile:23: recipe for target 'build' failed
make: *** [build] Error 127

------------------------------------------------------------------------


1/43 tests succeeded.

Tests failed.

**Comment by danmatichuk** [comment]
This seems unrelated to ProofCount, but my guess is that your VM is under-powered and as a result is hitting a timeout. You could try increasing the timeout in the build test script (misc/regression/tests.xml) or building the Word_Lib image manually without a timeout. i.e.

`isabelle/bin/isabelle build -d . -vb Word_Lib`

From the l4v directory.

**Comment by YakoubN** [comment]
Oh thanks that was exactly the solution for my VM problem.

**Comment by diegodiasm** [comment]
Dear Daniel, 

I read [1,2] and I am very interested in using proofcount to analyse a refinement algebra that I have mechanised in Isabelle/HOL. I tried to install proofcount for Isabelle-2015, but I did not succeed. Currently, I am using Isabelle-2016-1, and I read in this thread that you are working on a release of proofcount for Isabelle-2016-1. Do you have an idea of a date for release? Or, would you have a currently working version of proofcount that is compatible with Isabelle 2016-1? 

Thanks!

1. Empirical study towards a leading indicator for cost of formal software verification
2. Mining the Archive of Formal Proofs

**Comment by lsf37** [comment]
@diegodiasm sorry, this seems to have slipped by in the notification mechanism for an entire year.
Dan did work on an update for 2016-1 back then, but it was never fully finished. Since Dan has now graduated and we're no longer actively working on proofcount, we're planning to retire it from the repository. That means the last working version is the one for Isabelle-2016.
