### ISSUE TITLE
error building doc for haskell prototype

### ISSUE THREAD

**Issue by horaceb** [seL4/l4v#13]
I ran make in l4v/spec/haskell/doc and I got the following error:

figures/clientkernel.mp figures/clientkernel.mps

Sorry, I can't find the 'mpost' preload file; will try 'plain'.
I can't find the 'plain' preload file!
make: *** [figures/clientkernel.mps] Error 1

**Comment by Xaphiosis** [comment]
You need the texlive-metapost (or texlive-full) packages. See https://bugs.launchpad.net/ubuntu/+source/texlive-bin/+bug/1334143

**Comment by Xaphiosis** [comment]
If issue is resolved, could you please close? If not, consider letting us know what breakage remains.

**Comment by horaceb** [comment]
sorry, I forgot to close
