### ISSUE TITLE
 C- Parser install and use questions/ solved!

### ISSUE THREAD

**Issue by nasmtu** [seL4/l4v#17]
The environment variable $L4V_ARCH was not seen by invoking Isabelle by double clicking on it. But using the run from shell isabelle/bin/isabelle jedit  filename from the command shell it was seen and now I can see the output. 

Thanks

**Comment by talsewell** [comment]
Having a quick look at these reports, it does look like the INSTALL file in the c-parser directory is quite old, and possibly dates from when the parser was last released separately.

Isabelle needs to be pointed at the ROOTS file in l4v to build any of the l4.verified images or the ROOT file in c-parser to build the CParser image. The L4V_ARCH environment variable also needs to be set, which can be done in ~/.isabelle/etc/settings .

Good to hear you're making progress.

**Comment by AmerTahat** [comment]
In fact, I have become very interested in this work. The sel4 project is very inspiring, I really appreciate it so highly! 

Thanks a lot for your valued comments and collaboration! 
Amer
