### ISSUE TITLE
Some examples of using whileLoop in Monad_WP

### ISSUE THREAD

**Issue by LVPGroup** [seL4/l4v#23]
Dear,
Do you have some examples of using whileLoop in Monad_WP? 
In the source code, I only found the definition, but no examples and explaination. 
It is really not easy to follow it.

Thanks.

**Comment by talsewell** [comment]
The whileLoop combinator mostly exists to be used by AutoCorres as a state-monad equivalent to a while loop in C. I don't think it is used in the seL4 proofs.

The key unroll rule is proven in NonDetMonadLemmas [github.com/seL4/l4v/lib/Monad_WP/NonDetMonadLemmas.thy](url) - whileLoop_unroll - the while loop is equivalent to checking whether the condition currently holds, and if it does, performing one iteration of the loop plus the while loop. Isabelle wouldn't accept this as a recursive definition by default, thus the complicated definition.

The AutoCorres quickstart manual gives some example proofs involving whileLoop, e.g. in Chapter 2 [github.com/seL4/l4v/tools/autocorres/doc/quickstart/Chapter2_HoareHeap.thy] (url)

**Comment by lsf37** [comment]
The AutoCorres examples directory contains the examples in the quickstart tutorial, as well as a few other ones. An easy example of how to reason about whileLoop is in https://github.com/seL4/l4v/blob/master/tools/autocorres/tests/examples/ListRev.thy

While this is generated from a C file, the proof at the bottom is purely monadic.
