### ISSUE TITLE
c-parser timeout error

### ISSUE THREAD

**Issue by niuzhi** [seL4/l4v#313]
hello
l4v version：l4v-isabelle-2021,isabelle version:Isabelle2021

C-parser compile has this error,command is isabelle env make CParser. help me!thanks!
=====================================================
ubuntu@ubuntu:~/l4v-isabelle-2021/tools/c-parser$ export L4V_ARCH=X64
ubuntu@ubuntu:~/l4v-isabelle-2021/tools/c-parser$ isabelle env make CParser
/home/ubuntu/isabelle/bin/isabelle build -d ../.. -b -v CParser
Started at Thu Jul 22 09:11:37 GMT 2021 (polyml-5.8.2_x86_64_32-linux on ubuntu)
ISABELLE_TOOL_JAVA_OPTIONS="-Djava.awt.headless=true -Xms512m -Xmx4g -Xss16m"
ISABELLE_BUILD_OPTIONS=""

ML_PLATFORM="x86_64_32-linux"
ML_HOME="/home/ubuntu/isabelle/contrib/polyml-test-f86ae3dc1686/x86_64_32-linux"
ML_SYSTEM="polyml-5.8.2"
ML_OPTIONS="--minheap 500"

Session Pure/Pure
Session FOL/FOL
Session Tools/Tools
Session HOL/HOL (main)
Session HOL/HOL-Library (main timing)
Session HOL/HOL-Computational_Algebra (main timing)
Session HOL/HOL-Analysis (main timing)
Session HOL/HOL-Eisbach
Session HOL/HOL-Statespace
Session Lib/Word_Lib (lib)
Session Lib/Lib (lib)
Session C-Parser/Simpl-VCG
Session C-Parser/CParser
Building Word_Lib ...
Word_Lib: theory HOL-Eisbach.Eisbach
Word_Lib: theory HOL-Eisbach.Eisbach_Tools
Word_Lib: theory HOL-Library.Boolean_Algebra
Word_Lib: theory HOL-Library.Bit_Operations
Word_Lib: theory HOL-Library.Phantom_Type
Word_Lib: theory HOL-Library.Cardinality
Word_Lib: theory HOL-Library.Numeral_Type
Word_Lib: theory HOL-Library.Type_Length
Word_Lib: theory HOL-Library.Word
Word_Lib: theory Word_Lib.Bit_Comprehension
Word_Lib: theory Word_Lib.Hex_Words
Word_Lib: theory Word_Lib.Legacy_Aliases
Word_Lib: theory Word_Lib.More_Divides
Word_Lib: theory Word_Lib.Signed_Words
Word_Lib: theory Word_Lib.Word_Names
Word_Lib: theory Word_Lib.Type_Syntax
Word_Lib: theory Word_Lib.Word_Syntax
Word_Lib: theory HOL-Library.Signed_Division
Word_Lib: theory Word_Lib.Signed_Division_Word
Word_Lib: theory HOL-Library.Sublist
Word_Lib: theory HOL-Library.Prefix_Order
Word_Lib: theory Word_Lib.More_Sublist
Word_Lib: theory Word_Lib.Enumeration
Word_Lib: theory Word_Lib.Even_More_List
Word_Lib: theory Word_Lib.More_Arithmetic
Word_Lib: theory Word_Lib.More_Word
Word_Lib: theory Word_Lib.Enumeration_Word
Word_Lib: theory Word_Lib.Many_More
Word_Lib: theory Word_Lib.Distinct_Prop
Word_Lib: theory Word_Lib.Strict_part_mono
Word_Lib: theory Word_Lib.Traditional_Infix_Syntax
Word_Lib: theory Word_Lib.Bits_Int
Word_Lib: theory Word_Lib.Least_significant_bit
Word_Lib: theory Word_Lib.Norm_Words
Word_Lib: theory Word_Lib.Rsplit
Word_Lib: theory Word_Lib.Word_16
Word_Lib: theory Word_Lib.Word_EqI
Word_Lib: theory Word_Lib.Most_significant_bit
Word_Lib: theory Word_Lib.Generic_set_bit
Word_Lib: theory Word_Lib.More_Misc
Word_Lib: theory Word_Lib.Typedef_Morphisms
Word_Lib: theory Word_Lib.Aligned
Word_Lib: theory Word_Lib.Next_and_Prev
Word_Lib: theory Word_Lib.Word_Lemmas
*** Timeout
Word_Lib FAILED
(see also /home/ubuntu/.isabelle/Isabelle2021/heaps/polyml-5.8.2_x86_64_32-linux/log/Word_Lib)
*** Interrupt
Simpl-VCG CANCELLED
CParser CANCELLED
Unfinished session(s): CParser, Simpl-VCG, Word_Lib

Finished at Thu Jul 22 09:16:58 GMT 2021
0:05:20 elapsed time, 0:04:54 cpu time, factor 0.92
Makefile:42: recipe for target 'CParser' failed
make: *** [CParser] Error 142
ubuntu@ubuntu:~/l4v-isabelle-2021/tools/c-parser$ cat /home/ubuntu/.isabelle/Isabelle2021/heaps/polyml-5.8.2_x86_64_32-linux/log/Word_Lib
*** Interrupt
ubuntu@ubuntu:~/l4v-isabelle-2021/tools/c-parser$

**Comment by lsf37** [comment]
The port to Isabelle2021 is not finished yet, the main repository is still on Isabelle2020, and the isabelle-2021 branch is work in progress.

The shell prompt looks like you are using the `l4v` repository as a standalone repository. This is unlikely to work well. See the instructions in the README of <https://github.com/seL4/verification-manifest> to get a full setup including the correct Isabelle version for the corresponding l4v version.

**Comment by niuzhi** [comment]
hello @lsf37 ,I have pulled the file（verification-manifest/12.0.0.xml） according to the repo, but the following error still exists. Can you help?
===========================================================================
root@ubuntu:/home/ubuntu/verification# ls
graph-refine  HOL  isabelle  l4v  seL4

======================================================================
/home/ubuntu/verification/l4v/tools/c-parser/standalone-parser/../../../isabelle/bin/isabelle build -d ../.. -b -v CParser
Started at Fri Jul 23 07:19:16 GMT 2021 (polyml-5.8.1_x86_64_32-linux on ubuntu)
ISABELLE_BUILD_OPTIONS=""

ML_PLATFORM="x86_64_32-linux"
ML_HOME="/root/.isabelle/contrib/polyml-5.8.1-20200228/x86_64_32-linux"
ML_SYSTEM="polyml-5.8.1"
ML_OPTIONS="-H 1000 --maxheap 10000 --stackspace 64"

Session Pure/Pure
Session FOL/FOL
Session Tools/Tools
Session HOL/HOL (main)
Session HOL/HOL-Library (main timing)
Session HOL/HOL-Computational_Algebra (main timing)
Session HOL/HOL-Analysis (main timing)
Session HOL/HOL-Eisbach
Session HOL/HOL-Statespace
Session HOL/HOL-Word (main timing)
Session Lib/Word_Lib (lib)
Session Lib/Lib (lib)
Session C-Parser/Simpl-VCG
Session C-Parser/CParser
Building Word_Lib ...
Word_Lib: theory HOL-Eisbach.Eisbach
Word_Lib: theory HOL-Eisbach.Eisbach_Tools
Word_Lib: theory HOL-Library.Sublist
Word_Lib: theory HOL-Library.Prefix_Order
Word_Lib: theory Word_Lib.Hex_Words
Word_Lib: theory Word_Lib.Signed_Words
Word_Lib: theory Word_Lib.Norm_Words
Word_Lib: theory Word_Lib.WordBitwise_Signed
Word_Lib: theory Word_Lib.Word_Type_Syntax
Word_Lib: theory Word_Lib.Word_Syntax
Word_Lib: theory Word_Lib.Word_Lib
Word_Lib: theory Word_Lib.Enumeration
Word_Lib: theory Word_Lib.Word_Enum
Word_Lib: theory Word_Lib.Word_Setup_32
Word_Lib: theory Word_Lib.Word_Setup_64
Word_Lib: theory Word_Lib.HOL_Lemmas
Word_Lib: theory Word_Lib.More_Divides
Word_Lib: theory Word_Lib.Aligned
Word_Lib: theory Word_Lib.Word_Next
Word_Lib: theory Word_Lib.Word_EqI
Word_Lib: theory Word_Lib.Word_Lemmas
*** Timeout
Word_Lib FAILED
(see also /root/.isabelle/heaps/polyml-5.8.1_x86_64_32-linux/log/Word_Lib)
### theory "Word_Lib.Enumeration"
### 1.911s elapsed time, 1.871s cpu time, 0.096s GC time
Loading theory "Word_Lib.Word_Enum" (required by "Word_Lib.Word_Lemmas_32" via "Word_Lib.Word_Lemmas_Prefix" via "Word_Lib.Word_Lemmas")
instantiation
  word :: (len) enum
  enum_word == enum_class.enum :: 'a word list
  enum_all_word == enum_class.enum_all ::
    ('a word \<Rightarrow> bool) \<Rightarrow> bool
  enum_ex_word == enum_class.enum_ex ::
    ('a word \<Rightarrow> bool) \<Rightarrow> bool
instantiation
  word :: (len) enumeration_both
  enum_alt_word == enum_alt :: nat \<Rightarrow> 'a word option
### theory "Word_Lib.Word_Enum"
### 1.227s elapsed time, 1.211s cpu time, 0.000s GC time
Loading theory "Word_Lib.Word_Setup_32" (required by "Word_Lib.Word_Lemmas_32")
### theory "Word_Lib.Word_Setup_32"
### 0.131s elapsed time, 0.130s cpu time, 0.000s GC time
Loading theory "Word_Lib.Word_Setup_64" (required by "Word_Lib.Word_Lemmas_64")
### theory "Word_Lib.Word_Setup_64"
### 0.134s elapsed time, 0.134s cpu time, 0.000s GC time
Loading theory "Word_Lib.HOL_Lemmas" (required by "Word_Lib.Word_Lemmas_32" via "Word_Lib.Word_Lemmas_Prefix" via "Word_Lib.Word_Lemmas" via "Word_Lib.Word_EqI" via "Word_Lib.Word_Next" via "Word_Lib.Aligned")
### theory "Word_Lib.HOL_Lemmas"
### 3.275s elapsed time, 3.026s cpu time, 0.141s GC time
Loading theory "Word_Lib.More_Divides" (required by "Word_Lib.Word_Lemmas_32" via "Word_Lib.Word_Lemmas_Prefix" via "Word_Lib.Word_Lemmas" via "Word_Lib.Word_EqI" via "Word_Lib.Word_Next" via "Word_Lib.Aligned")
### theory "Word_Lib.More_Divides"
### 0.502s elapsed time, 0.386s cpu time, 0.000s GC time
Loading theory "Word_Lib.Aligned" (required by "Word_Lib.Word_Lemmas_32" via "Word_Lib.Word_Lemmas_Prefix" via "Word_Lib.Word_Lemmas" via "Word_Lib.Word_EqI" via "Word_Lib.Word_Next")
### theory "Word_Lib.Aligned"
### 10.004s elapsed time, 7.912s cpu time, 0.355s GC time
Loading theory "Word_Lib.Word_Next" (required by "Word_Lib.Word_Lemmas_32" via "Word_Lib.Word_Lemmas_Prefix" via "Word_Lib.Word_Lemmas" via "Word_Lib.Word_EqI")
### theory "Word_Lib.Word_Next"
### 5.701s elapsed time, 5.123s cpu time, 0.121s GC time
Loading theory "Word_Lib.Word_EqI" (required by "Word_Lib.Word_Lemmas_32" via "Word_Lib.Word_Lemmas_Prefix" via "Word_Lib.Word_Lemmas")
### theory "Word_Lib.Word_EqI"
### 7.590s elapsed time, 4.887s cpu time, 0.059s GC time
Loading theory "Word_Lib.Word_Lemmas" (required by "Word_Lib.Word_Lemmas_32" via "Word_Lib.Word_Lemmas_Prefix")
linarith_split_limit exceeded (current value is 9)
linarith_split_limit exceeded (current value is 9)
*** Interrupt
Simpl-VCG CANCELLED
CParser CANCELLED
Unfinished session(s): CParser, Simpl-VCG, Word_Lib

Finished at Fri Jul 23 07:22:14 GMT 2021
0:02:58 elapsed time, 0:02:12 cpu time, factor 0.74
Makefile:42: recipe for target 'CParser' failed
make: *** [CParser] Error 1

**Comment by niuzhi** [comment]
@lsf37  c-parser make conflict error.Could it be the build failure caused by this reason?
root@ubuntu:/home/ubuntu/zte/l4v/tools/c-parser# make c-parser-deps
mlton /home/ubuntu/zte/l4v/tools/c-parser/tools/mllex/mllex.mlb
/home/ubuntu/zte/l4v/tools/c-parser/tools/mllex/mllex StrictC.lex

Number of states = 955
Number of distinct rows = 687
Approx. memory size of trans. table = 708984 bytes
/home/ubuntu/zte/l4v/tools/c-parser/tools/mllex/mllex /home/ubuntu/zte/l4v/tools/c-parser/tools/mlyacc/src/yacc.lex

Number of states = 95
Number of distinct rows = 47
Approx. memory size of trans. table = 6063 bytes
mlton /home/ubuntu/zte/l4v/tools/c-parser/tools/mlyacc/mlyacc.mlb
/home/ubuntu/zte/l4v/tools/c-parser/tools/mlyacc/mlyacc StrictC.grm
1 shift/reduce conflict

**Comment by lsf37** [comment]
The shift-reduce conflict is only a warning and expected. It looks like this part has built fine, and it does look like you have the right configuration of repositories.

Which command are you using for starting the C parser build?  (the one that leads to the timeout)

It's possible that the timeout for Word_Lib is set a bit low for some machines. If you edit the file `l4v/lib/Word_Lib/ROOT` and change the `timeout` value on line 10 to `1500` instead, does it work then?

**Comment by lsf37** [comment]
If the reason is indeed a too-low timeout value and you are using the `run_tests` command in `l4v` to start the build, you can provide the command line option `--scale-timeouts 2` to double all timeout value (or use any other factor). This means you don't have to change multiple ROOT or test files.

**Comment by niuzhi** [comment]
@lsf37 I used C parser build command:make
[root@control-plane c-parser]# pwd
/root/verfication/code/l4v/tools/c-parser
[root@control-plane c-parser]# make

**Comment by lsf37** [comment]
Ok, no worries. `make` should work as well in this case. Is this inside a VM or docker container? How much memory and how many CPUs does it have?

**Comment by niuzhi** [comment]
@lsf37 The problem has been solved, thank you! This is a very good project. I am studying the use of Isabelle to verify the algorithm and protocol. Can you provide some learning documents to make it easier for me to use it? Thank you very much for your help

**Comment by niuzhi** [comment]
@lsf37 I come from China, and our team is currently working on proofs of theorems to verify complex algorithms, protocols and embedded systems. Can we invite you to share with us the relevant research points of isabelle and his use cases? It is convenient for us to promote the value of isabelle.

**Comment by lsf37** [comment]
Glad it worked.

In terms of documentation of Isabelle itself there is <https://isabelle.in.tum.de/documentation.html> and also the book Concrete Semantics <http://concrete-semantics.org>.

For the C Parser, there is not much, the [POPL'07 paper](https://ts.data61.csiro.au/publications/nictaabstracts/Tuch_KN_07.abstract.html) introduces the memory model used in it, but doesn't talk much about how to use the parser on a practical level.

[AutoCorres](https://ts.data61.csiro.au/software/TS/autocorres/index.html), which builds on top of the C parser and which I would recommend using for C verification, there is the [quickstart document](https://ts.data61.csiro.au/projects/TS/autocorres/quickstart.pdf) as well as David Greenaway's [PhD thesis](https://ts.data61.csiro.au/publications/nictaabstracts/Greenaway:phd.abstract.html) on the tool.

The later parts for the UNSW lecture [COMP4161](https://www.cse.unsw.edu.au/~cs4161/) deal with C verification with these two tools and might be helpful. The lecture slides and demo files are available from the [course website](https://www.cse.unsw.edu.au/~cs4161/).

Feel free to email me directly at my University address `kleing@unsw.edu.au` about your research. It's always interesting to hear about verification projects.
