### ISSUE TITLE
autocorres build failure.please help me!

### ISSUE THREAD

**Issue by niuzhi** [seL4/l4v#314]
@lsf37  hello,autocorres build failure, please help me!thank you very much!

root@ubuntu:/home/ubuntu/verification/l4v# L4V_ARCH=ARM misc/regression/run_tests.py AutoCorres
Running 3 test(s)...
  Started isabelle ...
  Finished isabelle                  passed      ( 0:00:33 real,  0:00:43 cpu,  0.49GB)
  Started CParser ...
  Finished CParser                   passed      ( 0:00:22 real,  0:00:46 cpu,  0.75GB)
  Started AutoCorres ...
  Finished AutoCorres                FAILED *    ( 0:01:15 real,  0:01:44 cpu,  1.68GB)

------------------------------------------------------------------------
TEST FAILED: AutoCorres

...
   'a -> Proof.state -> bool * (string * 'b list)
### 2.585s elapsed time, 2.559s cpu time, 0.000s GC time
Loading theory "Lib.Value_Abbreviation" (required by "AutoCorres.AutoCorres" via "AutoCorres.SimplConv" via "AutoCorres.L1Defs" via "AutoCorres.CCorresE" via "AutoCorres.NonDetMonadEx" via "Lib.NonDetMonadLemmaBucket" via "Lib.NonDetMonadVCG" via "Lib.NonDetMonadLemmas" via "Lib.NonDetMonad" via "Lib.Lib")
structure Value_Abbreviation:
  sig
    val value_and_abbreviation:
       Syntax.mode ->
         binding -> string -> bool -> Proof.context -> local_theory
  end
value_abbreviation_test_important_magic_number \<equiv> 16777184
value_abbreviation_test_range_of_options \<equiv>
[24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5]
### 1.148s elapsed time, 1.142s cpu time, 0.027s GC time
Loading theory "Lib.Lib" (required by "AutoCorres.AutoCorres" via "AutoCorres.SimplConv" via "AutoCorres.L1Defs" via "AutoCorres.CCorresE" via "AutoCorres.NonDetMonadEx" via "Lib.NonDetMonadLemmaBucket" via "Lib.NonDetMonadVCG" via "Lib.NonDetMonadLemmas" via "Lib.NonDetMonad")
consts
  delete :: "'a \<Rightarrow> 'a list \<Rightarrow> 'a list"
consts
  theRight :: "'a + 'b \<Rightarrow> 'b"
consts
  theLeft :: "'a + 'b \<Rightarrow> 'a"
consts
  opt_rel ::
    "('a \<Rightarrow> 'b \<Rightarrow> bool)
     \<Rightarrow> 'a option \<Rightarrow> 'b option \<Rightarrow> bool"
### 17.886s elapsed time, 17.549s cpu time, 0.730s GC time
*** exception THM 0 raised (line 105 of "global_theory.ML"):
*** Duplicate use of derivation identity for Lib.exception_set_finite_1 vs. Lib.exception_set_finite(1)
*** finite {x. ?P x} \<Longrightarrow>
*** finite {x. (x = ?y \<longrightarrow> ?Q x) \<and> ?P x}
*** At command "end" (line 2622 of "/home/ubuntu/verification/l4v/lib/Lib.thy")
Unfinished session(s): AutoCorres

Finished at Mon Jul 26 03:41:29 GMT 2021
0:01:11 elapsed time, 0:00:46 cpu time, factor 0.65
../../misc/isa-common.mk:45: recipe for target 'AutoCorres' failed
make: *** [AutoCorres] Error 2

**Comment by lsf37** [comment]
This failure in Lib sounds vaguely familiar. It has the flavour of an Isabelle version/l4v version mismatch. It could be picking up a Lib session from somewhere else in the file system or it could be picking up the wrong Isabelle version.

In the directory `l4v/isabelle`, what does `git status` give you as output?

When you run `./isabelle/bin/isabelle build -d . -l -n Lib` in directory `l4v`, does the list of files refer only to source files in the current `l4v` directory tree or are there others?

ps: for invoking the build, you shouldn't need to run the python script directly, `./run_tests -v AutoCorres` in `l4v` should work.
