### ISSUE TITLE
Autocorres on Win10

### ISSUE THREAD

**Issue by LVPGroup** [seL4/l4v#341]
I use Isabelle on Windows, and Autocorres 1.6.1. However, an error occured as follows:

install_C_file  "alloc.c"

The output tab shows: 
Illegal character ":" in path element "D:\temp\MLTEMPb06820"
The error(s) above occurred in "D:\temp\MLTEMPb06820"

How can I modify the sources to remove it?
Thanks.

**Comment by lsf37** [comment]
I don't have a Windows machine available to confirm this, but it looks to me like this path comes out of `tmpfile()` in this file:
<https://github.com/seL4/l4v/blob/349309ebf5c775db1bc5933fa214ad4cbb704165/tools/c-parser/isar_install.ML#L124-L125>

To confirm you could try running the `install_C_file` command without the C preprocessor 

```isabelle
declare [[cpp_path=""]]
install_C_file "alloc.c"
```

If that works and you don't need the preprocessor, then that is a good workaround. If you do need the preprocessor, then we would need to try to convert the windows path for the temp file into a POSIX path, which the rest of Isabelle expects.

**Comment by LVPGroup** [comment]
Resolved! Thanks. 
Actually, I have to install C preprocessor (of gcc) into Isabelle/Cygwin, and then change some WIN paths to POSIX style in "isa_install.ML".
