### ISSUE TITLE
Make ASpec error

### ISSUE THREAD

**Issue by thomasyonug** [seL4/l4v#365]
Hi, I'm an isabelle and seL4 beginner and try to make readable abstract spec, but I got below output when I ``` make ASpec ``` in macOS 11.4 and ubuntu21.04. Is there anyone who could help me figure it out? Thank you. :)
```
Started at Sun Sep 26 16:42:47 GMT+8 2021 (polyml-5.8.2_x86_64_32-darwin on Ivan)
ISABELLE_TOOL_JAVA_OPTIONS="-Djava.awt.headless=true -Xms512m -Xmx4g -Xss16m"
ISABELLE_BUILD_OPTIONS=""

ML_PLATFORM="x86_64_32-darwin"
ML_HOME="/Applications/Isabelle2021.app/contrib/polyml-test-f86ae3dc1686/x86_64_32-darwin"
ML_SYSTEM="polyml-5.8.2"
ML_OPTIONS="--minheap 500"

*** Bad parent session "HOL-Word" for "Word_Lib" (line 9 of "/Users/yangwenzhang/workspace/formalMethod/l4v/lib/Word_Lib/ROOT")
```

**Comment by thomasyonug** [comment]
Sorry, I think I didn't setup the system correctly

**Comment by mbrcknl** [comment]
At a guess, this is using the wrong version of Isabelle. The `HOL-Word` session comes from the Isabelle distribution, but `Word_Lib` comes with `l4v`, and the message suggests some incompatibility between them. And the environment variables printed above that suggest you're using Isabelle 2021 installed in `/Applications`. We're currently working on updating our proofs to work with Isabelle 2021.

If you use the `repo` tool to obtain the sources as described at [seL4/verification-manifest](https://github.com/seL4/verification-manifest), you'll get checkouts of a number of related repositories at matching versions, including the right version of Isabelle.

You might also need to look at [setup.md](https://github.com/seL4/l4v/blob/master/docs/setup.md) to install some dependencies.
