### ISSUE TITLE
Rename Word_Lib and Simpl sessions?

### ISSUE THREAD

**Issue by lsf37** [seL4/l4v#546]
The names Word_Lib, Simpl, and Separation_Algebra clash with existing AFP entry names (since they are copies).

This means one cannot have the AFP and l4v in ROOTS session scope at the same time, which can be annoying for people how work with both.

Should we rename the sessions or do we leave this problem for some other time?

**Comment by lsf37** [comment]
This is more relevant when Word_Lib and Simpl are factored out into a separate tools repository, because the probability increases that one might want to use that together with the rest of the AFP.

**Comment by lsf37** [comment]
Closing this as won't fix, because we've decided not to move these into a separate repo after all.

**Comment by adbrucker** [comment]
Renaming Word_Lib allows one to use AutoCorres with the full AFP installed. I did this in a fork: [https://github.com/adbrucker/lh-l4v/tree/renaming_Word_Lib](https://github.com/adbrucker/lh-l4v/tree/renaming_Word_Lib) that we used internally now for a couple of months without problems. Without this (IMHO relatively simple) change, using AutoCorres in a project that itself depends on several AFP entries feels like more work than necessary.

**Comment by lsf37** [comment]
We're planning to submit AutoCorres to the AFP in the next few months, which should resolve all of these problems.
