### ISSUE TITLE
check scheduled workflow runs

### ISSUE THREAD

**Issue by lsf37** [seL4/l4v#611]
It seems like we overlooked something when merging the binary verification trigger:

```
The workflow is not valid. .github/workflows/external.yml (Line: 47, Col: 12): Job 'binary-verification' depends on unknown job 'proofs'.
```

**Comment by lsf37** [comment]
We should check the weekly-clean file as well.

**Comment by mbrcknl** [comment]
The weekly-clean workflow has been running ok, e.g. https://github.com/seL4/l4v/actions/runs/4392866801.
