### ISSUE TITLE
sel4 verification

### ISSUE THREAD

**Issue by ambition-code** [seL4/l4v#618]
After I've built the sel4 validation environment and run run_tests, I want to use c-parser, but I don't know how to build the environment and run it, I can't find the specific reference documentation, can you tell me where it is? Thank you very much for your answers.

**Comment by lsf37** [comment]
Glad to help.

**Comment by ambition-code** [comment]
I am very sorry to bother you again. Now I want to run my c code on autocorres tool, but I have not found a proper document, which contains how I should do each step (what command to run) to convert the c code into isabelle code. I would be very grateful if you could help me.
