### ISSUE TITLE
Questions about the autocorres tool

### ISSUE THREAD

**Issue by ambition-code** [seL4/l4v#626]
When I want to try to use the autocorres tool to convert c language into Isabelle code, Isabelle prompts me bad theorey import: AutoCorres.AutoCorres, but I don't know what went wrong now. I would be very grateful if you could give me an answer.

**Comment by lsf37** [comment]
#627 seems to be asking the same question. Try the following:

If you have followed the instructions in [setup.md](https://github.com/seL4/l4v/blob/master/docs/setup.md), then from the directory l4v run the following command:

L4V_ARCH=ARM isabelle jedit -d . -l AutoCorres tools/autocorres/tests/examples/IsPrime.thy
to run the IsPrime example. The -d . tells Isabelle to use the ROOTS file in the l4v directory to find all necessary proof session that AutoCorres builds on. The -l AutoCorres tells it to use the AutoCorres session as a basis, and the tools/... file name says which theory file to load. L4V_ARCH=ARM means that it should use Arm AArch32 semantics for C, other options are AARCH64, RISCV64, and X64.

The first time it should pop up a window that says it is now going to build the AutoCorres session and its dependencies. This will take a while, but should only happen the first time you use -l AutoCorres for a specific L4V_ARCH.

**Comment by lsf37** [comment]
It looks like you are trying to import `stdarg.h`. Standard include files are very unlikely to conform to the subset of C that AutoCorres supports. It is written for low-level code that does not make use of the standard library.

**Comment by ambition-code** [comment]
Thank you for your quick and detailed reply! It helps me a lot.
