### ISSUE TITLE
Problems with the autocorres tool

### ISSUE THREAD

**Issue by goodoldboyyeah** [seL4/l4v#627]
When I open the examples directory under the autocorres directory, when I use isabelle jedit to open the Isabelle file, it prompts "bad theory import "autocorres.autocorres"" I don't know how to solve this problem now, if you can give me some suggestions, I will be very grateful gratitude.

**Comment by lsf37** [comment]
If you have followed the instructions in [setup.md][], then from the directory `l4v` run the following command:

```sh
L4V_ARCH=ARM isabelle jedit -d . -l AutoCorres tools/autocorres/tests/examples/IsPrime.thy
```

to run the `IsPrime` example. The `-d .` tells Isabelle to use the `ROOTS` file in the `l4v` directory to find all necessary proof session that AutoCorres builds on. The `-l AutoCorres` tells it to use the AutoCorres session as a basis, and the `tools/...` file name says which theory file to load. `L4V_ARCH=ARM` means that it should use Arm AArch32 semantics for C, other options are AARCH64, RISCV64, and X64.

The first time it should pop up a window that says it is now going to build the `AutoCorres` session and its dependencies. This will take a while, but should only happen the first time you use `-l AutoCorres` for a specific L4V_ARCH.

[setup.md]: https://github.com/seL4/l4v/blob/master/docs/setup.md
