### ISSUE TITLE
Cannot load theory file "l4v/proof/crefine/autocorres-test/Refine_C.thy"

### ISSUE THREAD

**Issue by LC-John** [seL4/l4v#662]
Hello. I am quite new to Isabelle and seL4, and my current project is somehow related to them. I have followed the instructions from [setup.md](https://github.com/seL4/l4v/blob/master/docs/setup.md). I can successfully run the proofs by ``L4V_ARCH=ARM ./run_tests``, and the outputs suggests that ``55/55 tests succeeded``.

However, when I try to generate the pdf documents by the command ``./isabelle/bin/isabelle build -D . -o document=pdf -o document_output=output -v`` (before this, I have run ``export L4V_ARCH=ARM''), there is an error shown as below.

```bash
...
...
Session Proofs/SimplExportAndRefine
Session Lib/LibTest (lib)
Session Specifications/TakeGrant
*** Cannot load theory file "/PATH/TO/SEL4/l4v/proof/crefine/autocorres-test/Refine_C.thy"
*** The error(s) above occurred for theory "AutoCorresCRefine.Refine_C"
*** (required by "AutoCorresCRefine.AutoCorresTest") (line 10 of "/PATH/TO/SEL4/l4v/proof/crefine/autocorres-test/AutoCorresTest.thy")
*** Cannot load theory file "/PATH/TO/SEL4/l4v/proof/crefine/autocorres-test/Refine_C.thy"
*** No such file: "/PATH/TO/SEL4/l4v/proof/crefine/autocorres-test/Refine_C.thy"
*** The error(s) above occurred in session "AutoCorresCRefine" (line 119 of "/PATH/TO/SEL4/l4v/proof/ROOT")
```

I found it quite odd, since in my understanding, after running ``./run_tests`` the whole project should be successfully built. I have also tried ``./isabelle/bin/isabelle build -d . -v -b AutoCorresCRefine`` to directly build the ``AutoCorresCRefine`` session, and a similar error is reported as below.

```bash
...
...
Session Proofs/CBaseRefine
Session Proofs/CRefine
Session Proofs/AutoCorresCRefine
*** Cannot load theory file "/PATH/TO/SEL4/l4v/proof/crefine/autocorres-test/Refine_C.thy"
*** The error(s) above occurred for theory "AutoCorresCRefine.Refine_C"
*** (required by "AutoCorresCRefine.AutoCorresTest") (line 10 of "/PATH/TO/SEL4/l4v/proof/crefine/autocorres-test/AutoCorresTest.thy")
*** Cannot load theory file "/PATH/TO/SEL4/l4v/proof/crefine/autocorres-test/Refine_C.thy"
*** No such file: "/PATH/TO/SEL4/l4v/proof/crefine/autocorres-test/Refine_C.thy"
*** The error(s) above occurred in session "AutoCorresCRefine" (line 119 of "/PATH/TO/SEL4/l4v/proof/ROOT")
```

All these experiments are carried out upon an Ubuntu 20.04 remote server. Could anyone please show me where I did it wrong?

**Comment by lsf37** [comment]
To answer the question where the build might have gone wrong (because it isn't actually failing on the document generation yet), the `isabelle build -D .` invocation looks suspicious. For Isabelle do find all session dependencies, the main `ROOTS` file at the root of the l4v repository has to be in scope for the build, so depending on which directory that command was issued in, you probably need something like `isabelle build -d ../.. <session-name>` or, if you invoke from the l4v root directory: `isabelle build -d . <session-name>` (even if the session is declared in some deeper directory)

**Comment by LC-John** [comment]
Appreciate your answer.
I tried to build the sessions of AutoCorresCRefine again, but it still failed. I run ``./isabelle/bin/isabelle build -d . -v AutoCorresCRefine`` from the l4v root directory. It still reported the same error message.
It seems to be something wrong, since I cannot find the file ``l4v/proof/crefine/autocorres-test/Refine_C.thy``.

**Comment by lsf37** [comment]
There is something strange about this: there is no session `AutoCorresCRefine` in the l4v repository, and invoking the command above should give you an error message that the session does not exist. There is also no directory `autocorres-test` in `proof/crefine` and if there were it would not contain a theory `Refine_C`.
