### ISSUE TITLE
Lib.find vs. List.find

### ISSUE THREAD

**Issue by diekmann** [seL4/l4v#9]
Hi,

I'm using l4v at revision 7e9b8224ee95874c517cbd5c9f28209d01c00360.

I noticed that in `Lib` there is a function `find` which is equal to Isabelle's `List.find` (loaded by Main).

Is there a specific reason for this?

**Comment by lsf37** [comment]
The reason probably is that the person who wrote it wasn't aware of List.find and was transliterating parts of the Haskell prelude many years ago.

It should be removed, will have a look at that. Thanks for letting us know!

**Comment by lsf37** [comment]
This is now removed in the word library cleanup branch. Will appear when this branch is pushed out.

**Comment by lsf37** [comment]
Now pushed out, see https://github.com/seL4/l4v/commit/6ca877b6612fa154cb6623b85232bdf2b5538226. Have fun ;-)
